// Code generated by "stringer -type ClauseKind -linecomment"; DO NOT EDIT.

package sqlbuilder

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_unknownClause-0]
	_ = x[_FromClause-1]
	_ = x[_JoinClause-2]
	_ = x[_LeftJoinClause-3]
	_ = x[_WhereClause-4]
	_ = x[_GroupByClause-5]
	_ = x[_OrderByClause-6]
}

const _ClauseKind_name = "_unknownClausefromjoinleft joinwheregroup byorder by"

var _ClauseKind_index = [...]uint8{0, 14, 18, 22, 31, 36, 44, 52}

func (i ClauseKind) String() string {
	if i >= ClauseKind(len(_ClauseKind_index)-1) {
		return "ClauseKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ClauseKind_name[_ClauseKind_index[i]:_ClauseKind_index[i+1]]
}
