// Code generated by "stringer -type StatementKind -linecomment"; DO NOT EDIT.

package sqlbuilder

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_unknownStatement-0]
	_ = x[_SelectStatement-1]
}

const _StatementKind_name = "_unknownStatementselect"

var _StatementKind_index = [...]uint8{0, 17, 23}

func (i StatementKind) String() string {
	if i >= StatementKind(len(_StatementKind_index)-1) {
		return "StatementKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatementKind_name[_StatementKind_index[i]:_StatementKind_index[i+1]]
}
